install boot2docker
install chisel
install docker
install grc
install hub
install reattach-to-user-namespace
install the_silver_searcher
install tmux
install tree
install wget
install xctool
install zsh

update
