install chisel
install docker
install flow
install gh
install git-extras
install grc
install reattach-to-user-namespace
install the_silver_searcher
install tmux
install tree
install xctool
install zsh

update
