export PATH="$HOME/.dotfiles/bin:/Usr/local/Cellar:/bin:/usr/local/bin:$HOME/.rbenv:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin"
export PATH="/Library/Developer/Toolchains:$PATH"

export DOTFILES=$HOME/Code/Dotfiles
export PROJECTS=$HOME/Code

# Source every .zsh file in this rep
for config_file ($DOTFILES/**/source/*.zsh) [[ "$(basename $config_file)" == "completion.zsh" ]] || source $config_file

fpath=(~/.zsh/completion $fpath)

# Initialize autocomplete here, otherwise functions won't be loaded
autoload -U compinit
compinit

# Enable extended globbing
setopt extendedglob

# Allow [ or ] whereever you want
unsetopt nomatch

# Let Hub take over
eval "$(hub alias -s)"

unsetopt flowcontrol

# Load every completion after autocomplete loads
for config_file ($DOTFILES/**/source/completion.zsh) source $config_file

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
